### ISSUE TITLE
How to create your custom App

### ISSUE THREAD

**Issue by jfm92** [micro-ROS/NuttX#12]
When you develop an App for NuttX, you can choose if your App is an example, a system utility, can utility..
The only difference beteween the diferents options, is in which folder you save your app.
To this guide, we're going to develop the App in the example folder.

So go to: `App/Examples`
And create a folder with the name of your App (In this case it'll be custom_app).
Each App have four basicall file:
![imagen](https://user-images.githubusercontent.com/13625726/36589361-4f70ad5a-188b-11e8-8858-9ad84e23e1d5.png)

- **custom_app_main.c** : This is the main file of the project. This file have acces to:
  - Header file of the driver.
  - Basic C/C++ library.
  - Basic NuttX library.
  - You can access to other files that you add to this folder.
- **Kconfig** : Here you programm the options that will appear at the menuconfig, such as the description, the name, dependencies...
- **Make.defs** : This file add this application when it's check in menu.
- **Makefile** : This file is use to add the exactly file to the compilation and which options do you want to have in the App and in the system when you're run it.

### Kconfig
The next image is the configuration of this App in the menu:
![imagen](https://user-images.githubusercontent.com/13625726/36593307-63733404-1899-11e8-818e-f5e3c8bbb793.png)

You can add some configuration options to your app that it'll appear in the menuconfig:
![imagen](https://user-images.githubusercontent.com/13625726/36590786-194d50c0-1890-11e8-9629-c73cade9778b.png)
In this case you can see the options of the priority of the task when it's running the App and the stack size.

### Make.defs
This file is like a linker.

![imagen](https://user-images.githubusercontent.com/13625726/36592946-120a6d2c-1898-11e8-81cc-20d23abbf1ce.png)

### Makefile
![imagen](https://user-images.githubusercontent.com/13625726/36593418-eceae1fa-1899-11e8-84af-fc5a95b6c398.png)

Now go to the previous folder,open the Kconfig file and add this line:
source "/home/juan/nuttxspace_add_app/apps/examples/custom_app/Kconfig"

## Main file
Now everything it's setup and it's only left to program your App.
This is a basic skeleton of an empty App
![imagen](https://user-images.githubusercontent.com/13625726/36597207-b13cf1fc-18a8-11e8-9df5-9a98b9f353c7.png)

(The file is already attached)

And this is a very simple example of how it works the device control in NuttX and how to apply to your app.
![imagen](https://user-images.githubusercontent.com/13625726/36597499-961122c6-18a9-11e8-9c81-e7ed8f3877d7.png)

This app, open both sensors (Pressure and Humidity/temperature), read the value of both and show in the console.

[custom_app_files.zip](https://github.com/microROS/NuttX/files/1751883/custom_app_files.zip)

**Comment by darauble** [comment]
Hi, I've run into some other problem, for which I cannot find a description, but this post seems relevant.

Let's say, I have two custom apps: APP1 and APP2. APP2 has underlying functionality of APP1, but different frontend. So in APP2 I'd like to include "app1.h", i.e. reuse source of APP1. Currently, of course, compilation fails, as "app1.h" is inaccessible for APP2.

How could I reuse sources from one app in another? Let's say, I don't care about actually linking same object files twice (no need for shared library). How can this be achieved? How to make APP1's headers/sources visible "publicly", what is the _correct_ way of doing this? (The way of putting reused source elsewere is _not an option_, only in APP1's directory.)

**Comment by imuguruza** [comment]
@jfm92 may be you could help here
I suggest you also checking NuttX [page](https://nuttx.org/doku.php?id=documentation) and its [google group](https://groups.google.com/forum/#!forum/nuttx).

**Comment by darauble** [comment]
I've come up with a solution like this:

CFLAGS += -I $(APPDIR)/examples/APP1

However, this does not look very nice for me, even though... it works.
