### ISSUE TITLE
How to use ADC in NuttX

### ISSUE THREAD

**Issue by jfm92** [micro-ROS/NuttX#24]
This is a guide of how to use the ADC in NuttX. This is focus in the Olimex-STM32-E407 board.
At this moment, it's only one ADC channel available, but you can add more channels if you needed, doing the next modifications:
`NuttX/configs/olimex-stm32-e407/src/stm32adc`
(Please download the last version of micro-ROS repository, because the original set the ADC channel to an already use channel)

Once you're in the file there are some important aspects:
![image](https://user-images.githubusercontent.com/13625726/39176921-4d71fac0-47ae-11e8-8b92-235a5f302f90.png)

**You can see the pins available for the ADC in:**
`NuttX/arch/arm/src/chip/chip/stm32f40xxx_pinmap.h`

![image](https://user-images.githubusercontent.com/13625726/39177875-aeb6d9de-47b0-11e8-96d5-dde8d63ad1da.png)

The ADC allow us differents working modes:
-DMA.
-Timer trigger.
-Sample saved in the buffer.

By default is set the third mode, but in this guide we will set the timer trigger mode (the only difference is to check or not the timer)
System Type -> STM32 Peripheral Support -> ADC3 (Check)
System Type -> STM32 Peripheral Support -> TIM1 (Check)
System Type -> STM32 Peripheral Support -> Timer Configuration -> Image:
![image](https://user-images.githubusercontent.com/13625726/39178502-291291c2-47b2-11e8-9890-527f19fd2fca.png)
Device Drivers->Analog Device(ADC/DAC) Support-> Analog-to-Digital Conversion (Checked)

With this configuration we have configure an ADC with a sampling frequency of 100 Hz.

The behaviour of this driver is exactly the same as other driver. So you can see the example ADC_Simple to see how to use basic functionality of the ADC or go to the ADC example which is more complex.

**Comment by kingadamlove** [comment]
Hello, I am learning how to set up the hardware timer trigger of ADC, but I don't know why it can't be successful, and I can only use software trigger. I guess it is the problem of ADC1 Timer Trigger, I set it to 4.Can you give me an answer?please
