### ISSUE TITLE
How to use SPI in your driver

### ISSUE THREAD

**Issue by jfm92** [micro-ROS/NuttX#29]
This guide is separate in 2 blocks:

- Functions to be use in your driver.
- Implementation of the driver in your particular board.

#### Functions to be use in your driver
This guide is base on the MRF522 driver, which is in NuttX\drivers\contactless\mrf522.c

##### Write
You can use two kinds of write: 1 Byte writing or write a block of data.
The difference between them is the function that send the data.
Writing a byte:
![image](https://user-images.githubusercontent.com/13625726/40662895-d4f41aea-6357-11e8-90b2-c11cd2327162.png)

Writing a block of data:
![image](https://user-images.githubusercontent.com/13625726/40663031-24a61304-6358-11e8-81f9-f5134bab5b04.png)

##### Read
To read a register of the device, we have two different options: Read registers of 1 Byte or a block of bytes.
![image](https://user-images.githubusercontent.com/13625726/40664896-3dbb7880-635c-11e8-96f6-3f7885ec6569.png)

And to read a block of data, do the next operation:
![image](https://user-images.githubusercontent.com/13625726/40665010-797d901a-635c-11e8-88fb-f489938ab58d.png)

#### Implementation of the driver in your particular board:

First we have the file stm32_mfrc522.c which is in NuttX\configs\olimex-stm32-e407\src. This file initialize the SPI bus and register the driver.
You must register this file in the same way as is describe in the developing guide of a driver.

In NuttX\configs\olimex-stm32-e407\include\board.h add the pin to be use as C\S like in the next image:
![image](https://user-images.githubusercontent.com/13625726/40666572-5bb354d0-6360-11e8-8379-f184b8562503.png)

(In different microcontroller, the configuration could be different)

Then go to NuttX\configs\olimex-stm32-e407\src\stm32_spi.c and in the function `void stm32_spidev_initialize(void)
`
Add the next lines to initialize the C\S pin:
![image](https://user-images.githubusercontent.com/13625726/40666862-0870f65a-6361-11e8-9d63-1da69a01da5f.png)

Finally in the function `void stm32_spi1select(FAR struct spi_dev_s *dev, uint32_t devid,
                      bool selected)`
Add the next lines to use that pin.
![image](https://user-images.githubusercontent.com/13625726/40667089-97f01cac-6361-11e8-8d99-33371ff16dc2.png)

If the actuator/sensor have interruption pin, and it's implemented in the driver, go to: NuttX\configs\olimex-stm32-e407\src\olimex-stm32-e407.h and add the next definition:
![image](https://user-images.githubusercontent.com/13625726/40667166-be980892-6361-11e8-9301-63bb68e03a8a.png)

**Comment by vmayoral** [comment]
Very good tutorial @jfm92!

**Comment by jfm92** [comment]
Thank you @vmayoral !
