### ISSUE TITLE
Micro-XRCE-DDS working in STM32L1Discovery board

### ISSUE THREAD

**Issue by jfm92** [micro-ROS/NuttX#30]
The aim of this issue is to explain the modifications necessary to make microRTPS work in a very constrain board such as the STM32L1 with 32KB of RAM.

It's available a config profile base on the Olimex config profile, theses are the most relevant modifications:

- We use two serial ports instead of one (One for communication and the other for microRTPS). The reason  to use this instead of the USB, is because:
    - This board doesn't have available yet the USB console.
    - The USB console have a bigger use of memory.
- There is an option that allow you to set the UDP stack option without adding the real stack.
- There is an error which detects the client as a command instead of an APP. We aren't sure at this moment the reason of this problem, but we found a way avoid it:

Go to examples/hello and add to the main `client_main(argc,argv)` as you can see in the attached file. Then in menuconfig, go to:
Application configuration -> Examples -> "Hello, World!" example (Check)
And set stack size to 8500. This will reserver 8.3KB of RAM for this APP.

Finally it's necessary to modify `MICRORTPS_MTU_SIZE` by suggestion of @julianbermudez .
So after the first compilation, do a `make clean` . 
And go to apps/micrortps/micro-RTPS-client/include/micrortps/client/xrce_client.h and modified it to 128.

With theses modifications, microRTPS should run.

**Comment by imuguruza** [comment]
@jfm92 please use `micro-XRCE-DDS` official name
