### ISSUE TITLE
 Problems in trying to use nuttx and micro-ROS for  EtherCAT device control

### ISSUE THREAD

**Issue by KevinHwangAi** [micro-ROS/NuttX#50]
Hello everyone.
I would like to raise a few questions about nuttx:
 Does nuttx send and receive raw socket have buffer mechanism for the receive() function get  response data in Ethernet DMA?

**Comment by iluetkeb** [comment]
How did you measure the time? Please be aware that clock_gettime in NuttX doesn't have a very high resolution. It depends on the MCU exactly how much, but the elapsed time above is exactly 10ms, which is kinda suspicious and could indicate that the RTC resolution is the issue.

In general, benchmarking computation times on MCUs is better done by counting cycles. This is unfortunately not trivial on NuttX, but maybe @tkolcon and his team have a good suggestion.

**Comment by iluetkeb** [comment]
Regarding your other questions, yes NuttX can buffer network communication. I don't know the exact name of the setting, but try digging around in menuconfig a bit to find it.

**Comment by KevinHwangAi** [comment]
After days of testing, no way has yet been found to control the device because the nuttx system does not support ethercat.
