### ISSUE TITLE
Any plan for new release?

### ISSUE THREAD

**Issue by imchangchang** [micro-ROS/NuttX#56]
Hi, I'd like to use the micro-ROS with NuttX on an stm32 board. I've ported the [NuttX 10.1.0](https://github.com/imchangchang/incubator-nuttx/releases/tag/nuttx-10.1.0) on my board. Next step I want to do a robot project with micro-ROS. 

I notice that this repository does not have any updates recently. I'm wondering is there any plan for this repository?

Thanks,
Chang

**Comment by pablogs9** [comment]
Hello @imchangchang, this repo is deprecated. You have instructions for integrating micro-ROS in the newest versions of Nuttx here: https://github.com/micro-ROS/micro_ros_nuttx_app
