### ISSUE TITLE
Olimex-STM32-E407 

### ISSUE THREAD

**Issue by jfm92** [micro-ROS/NuttX#6]
### Datasheet:
Board: https://www.olimex.com/Products/ARM/ST/STM32-E407/resources/STM32-E407.pdf
Microcontroller: http://www.st.com/content/ccc/resource/technical/document/datasheet/ef/92/76/6d/bb/c2/4f/f7/DM00037051.pdf/files/DM00037051.pdf/jcr:content/translations/en.DM00037051.pdf

### How to programm it:
JTAG connector with [ARM-USB-TINY-H](https://www.olimex.com/Products/ARM/JTAG/ARM-USB-TINY-H/) from Olimex.

### Debugging recommendation:
You can connect at the same time the JTag Cable and the serial cable to communicate with console at the same time (I use a TTL-232R-3V3 cable). Only it's necessary to connect the serial adapter to the USART2 and GND.
With GDB you can debug the code and add breakpoints and so.
This tutorial explain you how to use it:
https://acassis.wordpress.com/2015/05/22/using-openocd-and-gdb-to-debug-my-nuttx-port-to-lpc11xx/

### Serial Console:
USART2: PD6(RX), PD5(TX)
This is the default option. You can change for other USART.

### I2C1 Bus:
PB6(I2C1 Clock), PB7(I2C1 Data)
The rest of the I2C bus are still not implemented.

### CAN Bus(Not checked yet):
PB8 (CAN1_Rx), PB9 (CAN1_TX)

### SPI Bus(Not checked yet):
PC2(SPI2_MISO), PC3(SPI2_MOSI)

### On board Button:
PA0

### On board LED:
PC13

### Ethernet:
More details on the datasheet.

### Extra features:
This board allow you to connect extra features through the UEXT port. But It's necessary to change the pin map to make it compatible, because by default this board with Nuttx is not compatible.

**Comment by imuguruza** [comment]
Update: Olimex debugger link added
