### ISSUE TITLE
configure failure micro-ros application on NuttX with olimex-stm32-e407

### ISSUE THREAD

**Issue by lin123-stack** [micro-ROS/NuttX#61]
-     Ubuntu20.04
-     foxy
-    olimex-stm32-e407
-    nuttx
following the tutorial:https://micro.ros.org/docs/tutorials/core/first_application_rtos/nuttx/
my question: configure_firmware steps failed with the following message:
``--- stderr: rosidl_typesupport_microxrcedds_c_tests                           
CMake Error at CMakeLists.txt:26 (find_package):
  By not providing "Findrosidl_typesupport_microxrcedds_test_msg.cmake" in
  CMAKE_MODULE_PATH this project has asked CMake to find a package
  configuration file provided by "rosidl_typesupport_microxrcedds_test_msg",
  but CMake did not find one.
  Could not find a package configuration file provided by
  "rosidl_typesupport_microxrcedds_test_msg" with any of the following names:
    rosidl_typesupport_microxrcedds_test_msgConfig.cmake
    rosidl_typesupport_microxrcedds_test_msg-config.cmake
  Add the installation prefix of "rosidl_typesupport_microxrcedds_test_msg"
  to CMAKE_PREFIX_PATH or set "rosidl_typesupport_microxrcedds_test_msg_DIR"
  to a directory containing one of the above files.  If
  "rosidl_typesupport_microxrcedds_test_msg" provides a separate development
  package or SDK, be sure it has been installed.
---
Failed   <<< rosidl_typesupport_microxrcedds_c_tests [1.58s, exited with code 1]``

I don't know how to solve it？
Thank you for your help!

**Comment by pablogs9** [comment]
Duplicated https://github.com/micro-ROS/micro_ros_setup/issues/466
